### ISSUE TITLE
Extra space in conversion to Nemeth

### ISSUE THREAD

**Issue by NSoiffer** [liblouis/liblouisutdml#64] opened 2019-08-13 23:34 UTC
The general test (`mathml_nemeth\test_general_001.test`) fails:

Image | ![image](https://user-images.githubusercontent.com/1545836/62984218-3113ff80-bde7-11e9-8c8f-441a30f3cb4a.png)
------------ | ------------- 
Output |    <code>?1/2.P#!;0^2.P"?D.?/A+BSIN  .?# .K ?1/>A^2"-B^2"]#</code>
Expected | `?1/2.P#!;0^2.P"?D.?/A+BSIN .?# .K ?1/>A^2"-B^2"]#`

Note: for some reason, github is deleting the extra space when I view it (at least in preview mode). The output has _2_ spaces after `SIN`; there should only be one space.

**Comment by bertfrees** [comment] 2019-08-14 22:48
I put two no-break spaces to make it more clear where the issue is.

**Comment by NSoiffer** [comment] 2019-08-14 23:48
Good thinking! I'll use that next time I have a problem.

**Comment by hammera** [comment] 2023-06-22 07:11
@NSoiffer, the mathml_nemeth\test_general_001.test are now passed a feature branch, looks please pull request #96.
If the #96 pull request are merged, this issue will be fixed.

Hopefully this information is help for you,

Attila

**Comment by hammera** [comment] 2023-10-20 17:38
Boys, if the mathml_nemeth/general_001.test the affected testcase file this issue related, this test are now passed in Liblouis UTDML latest master branch version.
If this is the case, anybody please close this issue.

Kind regards,

Attila

**Comment by NSoiffer** [comment] 2023-10-26 21:09
I apologize, but I haven't been keeping up with the latest status. If someone is running the tests and it passes, then they should close the issue.

**Comment by egli** [comment] 2023-10-27 06:29
Fixed in #96

**Closed by egli** 2023-10-27 06:29 UTC
